name: Tests

on:
  workflow_call:
    inputs:
      rust-version:
        required: true
        type: string

jobs:
  test:
    name: Rust tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.rust-version }}
          override: true
      - uses: Swatinem/rust-cache@v1

      - name: Rust tests
        run: cargo test -- --test-threads=1
